Feat/financiamientos
Omicron-IIC3143/backend pull request #44
Opened 2022-06-11 00:14 UTC by vicentegonz

## What?
-Basic Finances (Founding) CRUD
-User & Project Delete refactor 
-Finances associations

## Why?
associations problems & to keep track of the user transactions clearly

## How?
-new seed, migration, model & route files
-updating deletes in projects & user
-removing eslint ignores
-adding routes into app

## Testing? (almost required)
using the new seeds yo can delete de user id 1 and see how all its projects and finances go to de user id 0 (deleted user), also when you delete a project, the project status should be updated to "deleted"

## Anything Else? (optional)
- minor eslint fixes

2022-06-11 00:50 UTC, smatus9 requested changes

2022-06-11 00:50 UTC, smatus9 commented on app.js
> +let finances = require('./routes/foundings');
Aca creo que seria bueno mantener consistencia en los nombres. Mantener finances o foundings

2022-06-11 00:50 UTC, smatus9 commented on routes/foundings.js
> +	prefix: '/finance'
Lo mismo que el comentario de arriba, mantener consistencia en los nombres por claridad.

2022-06-11 00:50 UTC, smatus9 commented on routes/foundings.js
> +// Delete project by id
```suggestion
// Delete founding by id
```

2022-06-11 00:50 UTC, smatus9 commented on routes/foundings.js
> +// Update project by id
```suggestion
// Update founding by id
```

2022-06-11 00:50 UTC, smatus9 commented on routes/projects.js
>  router.delete('/delete/:id', passport.authenticate('jwt', { session: false }), async (ctx) => {
Si esto es un update la ruta no debe ser un post o put?

2022-06-11 00:50 UTC, smatus9 commented on routes/users.js
>  		} else {
Porque esto esta comentado?

2022-06-11 00:50 UTC, smatus9 commented on seeders/20220519183001-demo-user.js
> +			id: 0,
Sequelize parte los ids desde 0 o 1? Porque si es desde 1 esto podria ser un problema

2022-06-11 21:38 UTC, vicentegonz commented on seeders/20220519183001-demo-user.js
> +			id: 0,
en local no me tira problema

2022-06-11 21:40 UTC, vicentegonz commented on routes/foundings.js
> +	prefix: '/finance'
el prefijo de la ruta lo dejaria porque tiene mas sentido y no afecta

2022-06-11 21:43 UTC, vicentegonz commented on routes/users.js
>  		} else {
se me fue borrarlo era para ver si las asociaciones estaban funcionando

2022-06-11 21:44 UTC, vicentegonz commented on routes/projects.js
>  router.delete('/delete/:id', passport.authenticate('jwt', { session: false }), async (ctx) => {
lo dejaria como delete para tener consistencia y saber que al mandar a esa ruta se esta "eliminando" el proyecto

2022-06-11 22:46 UTC, smatus9 commented on seeders/20220519183001-demo-user.js
> +			id: 0,
Entonces dejemoslo asi, pero tengamoslo en mente en caso de que haya un error en el servidor de dev

2022-06-11 22:47 UTC, smatus9 approved these changes

2022-06-12 23:47 UTC, absoto4 requested changes
Funciona super y exactamente como lo habíamos conversado. Solo dejo el comentario del nombre del modelo de los Financiamientos.

2022-06-12 23:47 UTC, absoto4 commented on migrations/20220609013730-create-founding.js
> +		await queryInterface.createTable('Foundings', {
Me hace ruido que se llame Foundings el modelo. Creo que un mejor nombre podría ser Funding o Financing

2022-06-13 00:41 UTC, absoto4 approved these changes

2022-06-13 00:41 UTC, merged